[package]
name = "bevy-pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
rand = "0.8"
probability = "0.17.0"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!